#!/usr/bin/env bash
set -euo pipefail

# 导出离线交付物：docker save + SHA-256 清单 + helm package。
# 输出目录 OFFLINE_DIR（默认仓库内 deploy/offline/veridex-offline）。
# 镜像清单固定取包内 images.txt（OFFLINE_DIR 自定义时读仓库默认包的清单）。
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
OFFLINE_DIR="${OFFLINE_DIR:-${ROOT_DIR}/deploy/offline/veridex-offline}"
IMAGES_FILE="${ROOT_DIR}/deploy/offline/veridex-offline/images.txt"
if [ ! -f "${IMAGES_FILE}" ]; then
  IMAGES_FILE="${OFFLINE_DIR}/images.txt"
fi

checksum() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1"; else shasum -a 256 "$1"; fi
}

command -v docker >/dev/null 2>&1 || { echo "export-images: docker required" >&2; exit 1; }
command -v helm >/dev/null 2>&1 || { echo "export-images: helm required" >&2; exit 1; }
test -f "${IMAGES_FILE}" || { echo "export-images: missing ${IMAGES_FILE}" >&2; exit 1; }

mkdir -p "${OFFLINE_DIR}/images" "${OFFLINE_DIR}/charts"
: > "${OFFLINE_DIR}/images.sha256"
echo "# generated by export-images.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "${OFFLINE_DIR}/images.sha256"

while read -r image; do
  case "${image}" in '' | '#'*) continue ;; esac
  docker image inspect "${image}" >/dev/null 2>&1 \
    || { echo "export-images: image not built locally: ${image}" >&2; exit 1; }
  file="${OFFLINE_DIR}/images/$(echo "${image}" | tr '/:' '__').tar"
  docker save -o "${file}" "${image}"
  checksum "${file}" | sed "s|${OFFLINE_DIR}/||" >> "${OFFLINE_DIR}/images.sha256"
  echo "exported ${image} -> ${file}"
done < "${IMAGES_FILE}"

helm package "${ROOT_DIR}/deploy/helm/veridex" -d "${OFFLINE_DIR}/charts" >/dev/null
chart_tgz="$(ls "${OFFLINE_DIR}"/charts/veridex-*.tgz | head -n1)"
checksum "${chart_tgz}" | sed "s|${OFFLINE_DIR}/||" >> "${OFFLINE_DIR}/images.sha256"
echo "packaged ${chart_tgz}"
echo "export-images: done -> ${OFFLINE_DIR}"
