apiVersion: v1
kind: Service
metadata:
  name: {{ include "veridex.fullname" . }}-web
  labels:
    {{- include "veridex.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "veridex.webSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
